### ISSUE TITLE
New release ? :)

### ISSUE THREAD

**Issue by blop** [mike-engel/jwt-cli#149]
Hello,

Thank you for your JWT CLI tool it's very helpful !
Just a quick note to ask if you could release a new version?

Installing via HomeBrew we still get the 4.0.0 version which misses all the amazing improvements done since last February.
Or should we install it some other way to have the 'latest' build ?

Regards,

Olivier

**Comment by mike-engel** [comment]
Hi @blop, thanks for the kind words! I have been delaying a new release, since it will include breaking changes. There are a few open PRs that originally started as breaking changes, so I was waiting for them. I believe that they'll be rewritten to be non-breaking, so I'll try and get a new release out soon 😄
