### ISSUE TITLE
`--secret` flag treats all values as file paths

### ISSUE THREAD

**Issue by aryounce** [mike-engel/jwt-cli#254]
### Summary

`--secret` option only treats passed string as a file path.

### Steps to reproduce

Use `--secret` with anything other than `@<filepath>` and the command strips the first character from the flag's parameter and treats the string as a file path.

### Expected behavior

Per the `--help` text; only treat arguments with an `@` prefix as a file path.

**Comment by aryounce** [comment]
Output of `jwt --version` is:
```
jwt 5.0.3
```

**Comment by mike-engel** [comment]
@aryounce thanks for your patience. Which algorithm are you using?

**Comment by aryounce** [comment]
@mike-engel here is a rough outline of my invocation. `...` indicates that some value is being provided (in case the each of these being set matters).

```
jwt encode \
  --alg RS256 \
  --aud 'https://oauth2.googleapis.com/token' \
  --kid "..." \
  --iss "..." \
  --exp "..." \
  --secret "@${tmp_dir}/private.key" \
  --payload "scope=https://www.googleapis.com/auth/..."
```

**Comment by mike-engel** [comment]
This is intentional for `RS*` and `PS*` algorithms. The secret must be a file, which is required to be prefixed with the `@` symbol for a path. We remove the first character, `@` to get the actual path of the key file. Here's where this happens [in code](https://github.com/mike-engel/jwt-cli/blob/12db4af6017c210560c0d293f0f5fc40359f9604/src/translators/encode.rs#L47). We could make this better, but for these algorithms a file is needed, not a string, and for consistency, we enforce the `@` prefix.
